Fix zoom nad when using scroll wheel
powsybl/powsybl-diagram-viewer pull request #19
Opened 2023-01-19 08:43 UTC by YenguiSeddik

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-19 09:28 UTC, bendaamerahm approved these changes
code review : ok 
test: ok

2023-01-19 10:21 UTC, jonenst commented on src/network-area-diagram-viewer.ts
> +                zoomMin: 0.1 / (this.depth === 0 ? 1 : this.depth),
maybe just this.depth+1 ?
1,1,2,3,4,5 vs
1,2,3,4,5,6

2023-01-19 15:34 UTC, EstherDarkish requested changes

2023-01-19 16:52 UTC, jonenst approved these changes

2023-01-19 17:08 UTC, bendaamerahm approved these changes

2023-01-20 09:56 UTC, EstherDarkish approved these changes

2023-01-20 10:04 UTC, merged