Two windings transformers can now have a popover
powsybl/powsybl-diagram-viewer pull request #23
Opened 2023-06-09 10:19 UTC by archendel

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
feature

**What is the current behavior?**
When hovering a line in a diagram, a callback will be called in order to display a tooltip

**What is the new behavior (if this is a feature change)?**
This behaviour is now the same for two windings transformers

2023-06-13 07:18 UTC, AbdelHedhili requested changes

2023-06-13 07:18 UTC, AbdelHedhili commented on src/single-line-diagram-viewer.ts
> +    lineId: string,
It becomes equipmentId ?

2023-06-13 07:18 UTC, AbdelHedhili commented on src/single-line-diagram-viewer.ts
> +        const svgLines = this.svgMetadata.nodes.filter((node) =>
svgEquipments ?

2023-06-13 07:18 UTC, AbdelHedhili commented on src/single-line-diagram-viewer.ts
> +            const svgLine = this.container?.querySelector('#' + equipment.id);
svgEquipment ?

2023-06-15 09:36 UTC, AbdelHedhili approved these changes

2023-06-15 16:34 UTC, etiennehomer approved these changes

2023-06-20 09:43 UTC, merged